### ISSUE TITLE
Issue #1: treshold para eliminar columnas con valores inexistentes

### ISSUE THREAD

**Issue by keyvhinng** [keyvhinng/loan-data-ml-project#3]
Este enunciado:
`print('Eliminando columnas con mas de 90% de valores perdidos...')`
No parece coincidir con lo expuesto en esta linea de codigo: 
`cols_elim = [x for x in data.columns if data[x].isnull().sum()/data.count().max()>=0.10]`

El código indica que se eliminan columnas que tienen valores nulos en por lo menos 10% de sus registros, pero el enunciado da entender que se eliminan columnas que tienen valores nulos en por lo menos 90% de sus registros

**Comment by LMuroyaT** [comment]
Ver ultimo commit del branco Preprocessing_Rv.
